const brgrData=[
    {
      name: "Tandoori Chicken Burger",
      description: "A flavorful tandoori chicken patty served with lettuce, tomato, onion, and mint yogurt sauce in a sesame seed bun.",
      price: 380,
      spice: "Medium",
      ingredients: ["Tandoori chicken patty, ", "Lettuce, ", "Tomato, ", "Onion, ", "Mint yogurt sauce, ", "Sesame seed bun."],
      image: "https://images.unsplash.com/photo-1512152272829-e3139592d56f?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      category:"burger",
      eat:"non-veg",
    },
    {
      name: "Spicy Chicken Tikka Burger",
      description: "Grilled chicken tikka marinated in spicy yogurt, served with sliced onions, cucumber, and tangy mint chutney in a soft bun.",
      price: 400,
      spice: "Hot",
      ingredients: ["Grilled chicken tikka, ", "Onion, ", "Cucumber, ", "Mint chutney, ", "Soft bun."],
      image: "https://images.pexels.com/photos/580612/pexels-photo-580612.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      category:"burger",
      eat:"non-veg",
    },
    {
      name: "Butter Chicken Burger",
      description: "Tender butter chicken pieces served in a buttery sauce with lettuce, tomato, onion, and creamy mayo in a brioche bun.",
      price: 300,
      spice: "Mild",
      ingredients: ["Butter chicken pieces, ", "Lettuce, ", "Tomato, ", "Onion, ", "Creamy mayo, ", "Brioche bun, "],
      image: "https://restaurantindia.s3.ap-south-1.amazonaws.com/s3fs-public/2023-11/BeFunky-collage%20%2863%29.jpg",
      category:"burger",
      eat:"non-veg",
    },
    {
      name: "Paneer Tikka Burger",
      description: "Grilled paneer tikka served with lettuce, tomato, onion, and tangy tamarind sauce in a whole wheat bun.",
      price: 250,
      spice: "Mild",
      ingredients: ["Grilled paneer tikka, ", "Lettuce, ", "Tomato, ", "Onion, ", "Tamarind sauce, ", "Whole wheat bun."],
      image: "https://images.pexels.com/photos/6006598/pexels-photo-6006598.jpeg?auto=compress&cs=tinysrgb&w=600",
      category:"burger",
      eat:"veg",
    },
    {
      name: "Veggie Masala Burger",
      description: "Spicy vegetable patty made with potatoes, peas, and carrots, served with lettuce, tomato, and spicy mayo in a multigrain bun.",
      price: 150,
      spice: "Medium",
      ingredients: ["Spicy vegetable patty, ", "Lettuce, ", "Tomato, ", "Spicy mayo, ", "Multigrain bun."],
      image: "https://images.pexels.com/photos/23744955/pexels-photo-23744955/free-photo-of-burger-served-in-a-restaurant.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      category:"burger",
      eat:"veg",
    },
    {
      name: "Aloo Tikki Burger",
      description: "Crispy potato patties flavored with Indian spices, served with sliced onions, tomato, and tangy ketchup in a sesame seed bun.",
      price: 190,
      spice: "Mild",
      ingredients: ["Crispy potato patties, ", "Onion, ", "Tomato, ", "Ketchup, ", "Sesame seed bun."],
      image: "https://d4t7t8y8xqo0t.cloudfront.net/resized/720X480/group%2F5976%2Fmenu620230819045940.jpg",
      category:"burger",
      eat:"veg",
    },
    {
      name: "Buffalo Chicken Wings",
      description: "Crispy juicy chicken wings coated with rich buffalo sauce.",
      price: 300,
      spice: "Medium",
      ingredients: ["Chicken wings, ","Buffalo sauce."],
      image: "https://images.unsplash.com/photo-1608039755401-742074f0548d?q=80&w=1935&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      category:"fries",
      eat:"non-veg",
    },
    {
      name: "Nashville Chicken Wings",
      description: "Crispy juicy chicken wings brushed with hot, spicy nashville sauce.",
      price: 350,
      spice: "Hot",
      ingredients: ["Chicken wings, ","Nashville sauce."],
      image: "https://mojo.generalmills.com/api/public/content/lu509t6xTk6dXXDHk7Zubg_gmi_hi_res_jpeg.jpeg?v=45975b44&t=466b54bb264e48b199fc8e83ef1136b4",
      category:"fries",
      eat:"non-veg",
    },
    {
      name: "Orange Chicken Wings",
      description: "Crispy juicy chicken infused with tangy orange flavour.",
      price: 325,
      spice: "Mild",
      ingredients: ["Chicken wings, ","Orange juice."],
      image: "https://grandbaby-cakes.com/wp-content/uploads/2021/06/Honey-Orange-BBQ-Wings-6.jpeg",
      category:"fries",
      eat:"non-veg",
    },
    {
      name: "French Fries",
      description: "Crispy potato fries.",
      price: 200,
      spice: "Mild",
      ingredients: ["Potato."],
      image: "https://images.unsplash.com/photo-1573080496219-bb080dd4f877?q=80&w=1887&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      category:"fries",
      eat:"veg",
    },
    {
      name: "Potato Wedges",
      description: "Spicy potato wedges.",
      price: 240,
      spice: "Medium",
      ingredients: ["Potato."],
      image: "https://images.unsplash.com/photo-1529589510304-b7e994a92f60?q=80&w=1887&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      category:"fries",
      eat:"veg",
    },   
    {
      name: "Cola",
      description: "Coca cola.",
      price: 200,
      ingredients: ["Coca cola."],
      image: "https://images.unsplash.com/photo-1627260110809-df22a915242b?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      category:"drinks",
      eat:"veg",
    }, 
    {
      name: "Mint Mojito",
      description: "Refreshing mojito with the strength to cool you down.",
      price: 200,
      ingredients: ["Mint, ","Sprite, ","Lemon."],
      image: "https://images.unsplash.com/photo-1509448613959-44d527dd5d86?q=80&w=2035&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      category:"drinks",
      eat:"veg",
    }, 
    {
      name: "Chocolate shake",
      description: "Cool and thick chocolate shake.",
      price: 300,
      ingredients: ["Chocolate, ","Oreo, ","Milk, ","Sprinkles."],
      image: "https://images.unsplash.com/photo-1541658016709-82535e94bc69?q=80&w=2069&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      category:"drinks",
      eat:"veg",
    }, 
    {
      name: "Chocolate Almond Ice Cream",
      description: "Chocolate icecream with fresh crunchy almonds and oreo.",
      price: 350,
      ingredients: ["Chocolate, ","Almonds, ","Oreo."],
      image: "https://images.unsplash.com/photo-1642646689566-60c53a8c1ef4?q=80&w=1887&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      category:"sweet",
      eat:"veg",
    }, 
    {
      name: "Fruit Salad",
      description: "Assorted fruits in a creamy sweet dressing.",
      price: 400,
      ingredients: ["Fruits, ","Whipped cream, ","Dry fruits."],
      image: "https://www.thequickjourney.com/wp-content/uploads/2022/08/fruit-salad-with-cool-whip-04.jpg",
      category:"sweet",
      eat:"veg",
    },  

]

module.exports = { data: brgrData};
